classOrder = [
	"Signal",
	"Connection"
]

gitSourceBranch = "main"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Security"
description = "NewSignal handles all edge cases for you while still being as performant as possible. The edge case handling architecture makes it able to be always predictable."

[[home.features]]
title = "Familiar API"
description = "NewSignal is designed to have a Familiar API by mirroring BindableEvents, as well as other common signal modules such as GoodSignal, while also having additional features which add on top of the basic functionality."

[[home.features]]
title = "NewSignal.get()"
description = "NewSignal provides a simple way to use the same signals across different parts of your game by providing a global registry for an easier access."

[docusaurus]
title = "NewSignal"
tagline = "Signal implementation for Roblox"
